version: 2
jobs:
  build:
    working_directory: ~/graphql-xtext
    docker:
      - image: circleci/openjdk:8-jdk-stretch

    steps:
      - checkout
      - restore_cache:
          # ignoring target, tests, ui project POMs (very few changes, if any)
          key: v1-deps-{{ checksum "pom.xml" }}-{{checksum "com.intuit.graphql.parent/pom.xml" }}-{{checksum "com.intuit.graphql.parent/com.intuit.graphql/pom.xml" }}-{{ checksum "com.intuit.graphql.parent/com.intuit.graphql.ide/pom.xml" }}

      - run:
          name: Maven Build
          command: mvn install
      - save_cache:
          paths:
            - ~/.m2
          key: v1-deps-{{ checksum "pom.xml" }}-{{checksum "com.intuit.graphql.parent/pom.xml" }}-{{checksum "com.intuit.graphql.parent/com.intuit.graphql/pom.xml" }}-{{ checksum "com.intuit.graphql.parent/com.intuit.graphql.ide/pom.xml" }}

      - store_test_results:
          path: com.intuit.graphql.parent/com.intuit.graphql.tests/target/surefire-reports

      - store_artifacts:
          path: com.intuit.graphql.parent/com.intuit.graphql/target/com.intuit.graphql-1.0.0-SNAPSHOT.jar
      - store_artifacts:
          path: com.intuit.graphql.parent/com.intuit.graphql.ide/target/com.intuit.graphql.ide-1.0.0-SNAPSHOT.jar
      - store_artifacts:
          path: com.intuit.graphql.parent/com.intuit.graphql.ide/target/com.intuit.graphql.ide-1.0.0-SNAPSHOT-ls.jar
      - store_artifacts:
          path: com.intuit.graphql.parent/com.intuit.graphql.tests/target/com.intuit.graphql.tests-1.0.0-SNAPSHOT.jar
      - store_artifacts:
          path: com.intuit.graphql.parent/com.intuit.graphql.ui/target/com.intuit.graphql.ui-1.0.0-SNAPSHOT.jar

  #####
  # DEPLOY STEP
  #####

workflows:
  version: 2
  ci_builds:
    jobs:
      - build
#      - deploy:
#          requires:
#            - build
#          filters:
#            branches:
#              only: master

