version: 2
jobs:
  branch_builds:
    working_directory: ~/graphql-xtext
    docker:
      - image: circleci/openjdk:8-jdk-stretch

    steps:
      - checkout
      - run:
          name: test
          command: mvn test
      - store_test_results:
          path: com.intuit.graphql.parent/com.intuit.graphql.tests/target/surefire-reports
  master_build:
    working_directory: ~/graphql-xtext
    docker:
      - image: circleci/openjdk:8-jdk-stretch
    steps:
      - checkout
      - run:
          name: build
          command: mvn install
      - store_test_results:
          path: com.intuit.graphql.parent/com.intuit.graphql.tests/target/surefire-reports

      - store_artifacts:
          path: com.intuit.graphql.parent/com.intuit.graphql/target/com.intuit.graphql-1.0.0-SNAPSHOT.jar
      - store_artifacts:
          path: com.intuit.graphql.parent/com.intuit.graphql.ide/target/com.intuit.graphql.ide-1.0.0-SNAPSHOT.jar
      - store_artifacts:
          path: com.intuit.graphql.parent/com.intuit.graphql.ide/target/com.intuit.graphql.ide-1.0.0-SNAPSHOT-ls.jar
      - store_artifacts:
          path: com.intuit.graphql.parent/com.intuit.graphql.tests/target/com.intuit.graphql.tests-1.0.0-SNAPSHOT.jar
      - store_artifacts:
          path: com.intuit.graphql.parent/com.intuit.graphql.ui/target/com.intuit.graphql.ui-1.0.0-SNAPSHOT.jar

workflows:
  version: 2
  branch_builds:
    jobs:
      - master_build:
          filters:
            branches:
              only: master
      - branch_builds:
          filters:
            branches:
              only: ^(?!master)$
